### PR TITLE
Add Redux Slices to Project

### PR DESCRIPTION
**Pull request by adamilare**
In this update, the following are implemented;
- Add slice for books
- Add slice for categories
- Created Redux store

### CODE REVIEW

**Review by OyePriscilla — COMMENTED** [review]
Hi @adamilare , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**You have submitted a project, that does not have a descriptive branch name. The branch name suppose to be a summary of what you've done in the PR (may be `add reducers and actions`, `actions and reducers in React` ...).**.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by adamilare** [comment]
@OyePriscilla Thank you for your review.
I am using GitFlow, reason I am reusing an old branch.

Can you please clarify if any requirement on this review states it must be on a new branch?
What about other updates if I create a new branch just for this review?

Please let me have your view on this.

**Comment by OyePriscilla** [comment]
> @OyePriscilla Thank you for your review. I am using GitFlow, reason I am reusing an old branch.
> 
> Can you please clarify if any requirement on this review states it must be on a new branch? What about other updates if I create a new branch just for this review?
> 
> Please let me have your view on this.

@adamilare Please kindly create a new branch and mention this PR in the new PR.

**Comment by julie-ify** [comment]
Hi @adamilare,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### The previous reviewer suggested you create a new branch with a more descriptive name and work on that - unless of course, you can rename this branch to be more descriptive then there is no problem. It is part of [the general requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) that your branch name is descriptive of the feature you worked on, e.g. `reducer-actions`, `add-reducer-and-actions`, etc.

#### Generally, there is no need to reuse old branches given that they are being used for different projects and features. If you worked on a branch and merged to dev, when you want to work on a new feature it makes sense that you create a new branch off the dev branch as it will have all the previous changes.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by adamilare** [comment]
@julie-ify  Thank you for your review.

I personally do not see the reason why a branch's name must comply with a pull request when the same branch is going to be used for other features. I have tried working with several branches per project during GithubFlow.

I am going to take this up with Microverse because I am not comfortable creating multiple branches for a project. What is the use of Git bisect if multiple branches have to be created with few commits?

**Comment by julie-ify** [comment]
Hi @adamilare alright. You can request a second opinion from a senior reviewer using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

I, personally, don't understand the issue of creating different branches for different projects. I think it is good practice and also serves as a good tracker for different stages of development for the encompassing project.

When working with other people as well on a project (irrespective of Github or git flow), it is often the case that different branches are created for different features.

It can also be the case that one is working on multiple features on different branches simultaneously for the same project - in some cases, it wouldn't make much sense to do that on just one branch.

In practice, git bisect is often used to fish out bugs.

Regardless, since you disagree kindly request a second review using the form I shared earlier. Have a nice day!

**Comment by adamilare** [comment]
@julie-ify Thank you for your insight

**Pull request closed without merging**
